spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecom?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update  # Hoặc validate cho prod
    show-sql: true